# Generated by Django 5.0.1 on 2024-01-18 17:28

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='blog/images/defoult.jpeg', force_format='JPEG', keep_meta=True, quality=100, scale=1, size=[570, 365], upload_to='blog/images/'),
        ),
    ]
